### ISSUE TITLE
Determine why /widgets/events/day/* is being requested

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie-events#11]
The error logs are full of things like this:

```
2014-10-08 14:47:10 Error: [MissingActionException] Action WidgetsController::events() could not be found.
Exception Attributes: array (
  'controller' => 'WidgetsController',
  'action' => 'events',
)
Request URL: /widgets/events/day/10/26/2014
Stack Trace:
#0 /home/okbvtfr/public_html/muncie_events/lib/Cake/Routing/Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 /home/okbvtfr/public_html/muncie_events/lib/Cake/Routing/Dispatcher.php(162): Dispatcher->_invoke(Object(WidgetsController), Object(CakeRequest), Object(CakeResponse))
#2 /home/okbvtfr/public_html/muncie_events/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
```

I can't find anything in any views or controllers that would send people to a URL like that. So what the fuck.

**Comment by ericadeefox** [comment]
This issue cannot be recreated in Cake3 version of site. Guess whatever was making this happen wasn't migrated over.

**Comment by PhantomWatson** [comment]
That would be because the CakePHP 3 version of the site isn't live. Those requests were coming from other visitors / bots.
